/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#813646",
        "primary-container": "#9e4d5d",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffdde1",
        "primary-fixed": "#ffd9de",
        "primary-fixed-dim": "#ffb2be",
        "on-primary-fixed": "#3e0215",
        "on-primary-fixed-variant": "#772e3e",
        
        "secondary": "#6a5c49",
        "secondary-container": "#f3e0c7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#70624f",
        "secondary-fixed": "#f3e0c7",
        "secondary-fixed-dim": "#d6c4ac",
        "on-secondary-fixed": "#241a0b",
        "on-secondary-fixed-variant": "#514533",
        
        "tertiary": "#7c3948",
        "tertiary-container": "#98515f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffdde1",
        "tertiary-fixed": "#ffd9de",
        "tertiary-fixed-dim": "#ffb2be",
        "on-tertiary-fixed": "#3b0616",
        "on-tertiary-fixed-variant": "#723240",
        
        "surface": "#fbf8ff",
        "surface-dim": "#dbd9e1",
        "surface-bright": "#fbf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2fb",
        "surface-container": "#efecf5",
        "surface-container-high": "#eae7ef",
        "surface-container-highest": "#e4e1ea",
        "surface-variant": "#e4e1ea",
        
        "on-surface": "#1b1b21",
        "on-surface-variant": "#534345",
        "inverse-surface": "#303036",
        "inverse-on-surface": "#f2eff8",
        
        "outline": "#867274",
        "outline-variant": "#d9c1c3",
        "surface-tint": "#944555",
        
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        serif: ["'Playfair Display'", "Georgia", "serif"],
        display: ["'Playfair Display'", "Georgia", "serif"],
        sans: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        title: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        body: ["'Inter'", "system-ui", "sans-serif"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "space-3xl": "6rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "3rem",
        "margin-mobile": "1.25rem",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px",
      },
      boxShadow: {
        'subtle': '0 4px 20px -2px rgba(158, 77, 93, 0.05), 0 2px 8px -1px rgba(30, 30, 36, 0.03)',
        'elevated': '0 12px 32px -4px rgba(110, 45, 60, 0.10), 0 4px 12px -2px rgba(30, 30, 36, 0.05)',
        'featured': '0 20px 48px -6px rgba(129, 54, 70, 0.22), 0 8px 24px -4px rgba(30, 30, 36, 0.08)',
      }
    },
  },
  plugins: [],
};
